plugins {
  id 'java'
  id 'io.micronaut.application' version '4.6.1'
  id 'com.gradleup.shadow' version '8.3.9'
}

repositories {
    mavenCentral()
   // maven { url "https://repo.gradle.org/gradle/libs-releases" }
}

micronaut {
  version = '4.6.1'
  runtime('lambda_java')
  processResources {
    filesMatching('application.yml') {
      expand(project.properties)
    }
  }
}

dependencies {
  implementation platform('io.micronaut.aws:micronaut-aws-bom:4.6.1')
  testImplementation('io.micronaut.test:micronaut-test-junit5')
}

