<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>NumberLambda</AssemblyName>
    <RootNamespace>NumberLambda</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.6.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.2.0" />
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="2.3.0" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="8.0.0" />
  </ItemGroup>
</Project>