<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
 <modelVersion>4.0.0</modelVersion>
 <groupId>org.mule</groupId>
 <artifactId>accounts-salesforce-app</artifactId>
 <version>1.0.0</version>
 <packaging>mule-application</packaging>
 <name>accounts-salesforce-app</name>
 <properties>
 <mule.version>4.4.0</mule.version>
 <mule.maven.plugin.version>3.5.0</mule.maven.plugin.version>
 </properties>
 <build>
 <plugins>
 <plugin>
 <groupId>org.mule.tools.maven</groupId>
 <artifactId>mule-maven-plugin</artifactId>
 <version>${mule.maven.plugin.version}</version>
 <extensions>true</extensions>
 </plugin>
 </plugins>
 </build>
</project>